- id: extract-exercise-list
  name: Extract exercise list from any Markdown in docs/ to docs/exercises.md
  entry: extract-exercise-list
  language: python
  files: ^docs/
  types: [markdown]
  exclude: ^docs/exercises.md
  pass_filenames: false
