- id: extract-exercise-list
  name: Extract exercise list from any Markdown in docs/ to docs/exercises.md
  # Entry should be the script extract-exercise-list in the root of the repository
  entry: uv run extract-exercise-list
  language: python
  files: ^docs/
  types: [markdown]